# Default values for pact-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dius/pact-broker
  tag: 2.18.0-2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - pact.halfpipe.io
  tls:
  - secretName: star-halfpipe-io-tls
    hosts:
    - pact.halfpipe.io

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
