resources:
- name: pact-go-example
  type: git
  check_every: 10m
  source:
    uri: git@github.com:springernature/pact-go-example.git
    private_key: ((github.private_key))
    paths:
      - consumer-a/**
resource_types: []
jobs:
- name: consumer-a-test
  serial: true
  plan:
  - get: pact-go-example
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.10-stretch
      run:
        path: /bin/sh
        args:
        - -ec
        - |-
          ./pact-go-example/consumer-a/test.sh
      params:
        PACT_BROKER_USERNAME: ((pact.username))
        PACT_BROKER_PASSWORD: ((pact.password))
      inputs:
      - name: pact-go-example
        path: ""

