resource_types:
- name: pact-broker
  type: docker-image
  source:
    repository: platformengineering/concourse-pact-broker-resource
    tag: latest
resources:
- name: pact-go-example
  type: git
  source:
    uri: git@github.com:springernature/pact-go-example.git
    private_key: ((github.private_key))
    paths:
      - provider/**
- name: pact-consumer-a
  type: pact-broker
  source:
    pact_broker_url: https://pact.halfpipe.io
    pacticipant: Example-Consumer-A
- name: pact-consumer-b
  type: pact-broker
  source:
    pact_broker_url: https://pact.halfpipe.io
    pacticipant: Example-Consumer-B
jobs:
- name: provider-test
  serial: true
  plan:
  - get: pact-go-example
    trigger: true
  - get: pact-consumer-a
    trigger: true
  - get: pact-consumer-b
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.10-stretch
      run:
        path: /bin/sh
        args:
        - -ec
        - |-
          ./pact-go-example/provider/test.sh
      inputs:
      - name: pact-go-example
        path: ""

