resource_types:
- name: pact-broker
  type: docker-image
  source:
    repository: eu.gcr.io/halfpipe-io/pact-broker-resource
    password: ((gcr.private_key))
    tag: latest
    username: _json_key
resources:
- name: pact-go-example
  type: git
  source:
    uri: git@github.com:springernature/pact-go-example.git
    private_key: ((github.private_key))
    paths:
      - provider/**
- name: pact-broker-trigger
  type: pact-broker
  source:
    pact_broker_url: https://pact.halfpipe.io
    username: ((pact.username))
    password: ((pact.password))
    provider: Example-Provider
jobs:
- name: provider-test
  serial: true
  plan:
  - get: pact-go-example
    trigger: true
  - get: pact-broker-trigger
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.10-stretch
      run:
        path: /bin/sh
        args:
        - -ec
        - |-
          ./pact-go-example/provider/test.sh
      params:
        PACT_BROKER_USERNAME: ((pact.username))
        PACT_BROKER_PASSWORD: ((pact.password))
      inputs:
      - name: pact-go-example
        path: ""

